name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Android APK
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
