name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: kivy/buildozer-action@v0.4.0
      id: buildozer
      with:
        filename: buildozer.spec
        command: android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
